### PR TITLE
[Project] OSX, tvOS, and watchOS targets added

### PR DESCRIPTION
**Pull request by dehesa**
Hi,

I performed several changes in this pull request. Mainly I made the library support OSX, tvOS, and watchOS :)

These are the changes:
- Targets for OSX, tvOS, and watchOS.
- Added configuration files to easily tweak all the targets.
- Change the licensing from each file to the Info plist, thus the ugly header need not be repeated.
- The version and build number can now be controlled from the common.xcconfig. The changes there will be shown on all targets.

### CODE REVIEW

**Comment by Ben-G** [comment]
Thx a bunch, would be great to add framework targets for all platforms! 

In the past I've been simply sharing one `.plist` between all targets, avoiding a duplication of the values (see setup in ReSwift: https://github.com/reswift/reswift). That way I also don't need a custom `.xcconfig`.

What do you think of that approach? It might be less pure than providing separate configuration files.

Also, I presume this copyright notice slipped into the `xcconfig` by mistake? ;)

```
FRAMEWORK_LICENSE = Copyright © 2016 Relayr. MIT License.
```

Do you have any experience how the `xcconfig` files work with Carthage/CococaPods?

**Comment by dehesa** [comment]
Hi Ben,

Extremely sorry about the Licensing stuff. I have an Xcode template to create .xcconfigs and info.plist. I should have checked more carefully. Terribly ashamed! :(

I usually like to keep every target with its own Info.plist, since there are always tweaks here and there specifically for each one. However, this library is pretty small and it doesn't make much sense to have it separated. So yes, it may "decluter" things a bit.

If I remember well, Carthage just watch for the targets (through xcodebuild) or retrieve the binaries directly from Github. Thus, it should be any problem to have .xcconfig files. I don't know about CocoaPods, though. I don't expect it to be a problem, since major libraries like ReactiveCocoa, use xcconfig files extensively.

Should I resend the pull request with the fixes?

**Comment by Ben-G** [comment]
No worries :smiley: It looked very much like your default setting.

Could you rename copyright to `Benjamin Encz`? Then you could simply squash these 3 commits into one and I can merge.

Thanks a lot for this PR :star2:

**Comment by dehesa** [comment]
I've unified the info.plist and the .xcconfigs. Now looks better!
I have also fixed the licensing 😬 Be aware that I have signed the framework with the bundle signature BENC (in the .xcconfig). I don't know if that is what you usually use.

**Comment by Ben-G** [comment]
@dehesa What are the implications of the BENC signature? Haven't used/seen that setting before!

**Comment by dehesa** [comment]
It is an entry of the Info.plist referencing `CFBundleSignature`. As far as I know is more legacy than anything else. However, it is interesting that Xcode still creates an entry on the Info.plist on every project. It goes and fills it up with `???` (it must be 4 letters) and waits for you to change it (few do).  You can get more information in the [Information Property List Key Reference](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html).

I usually use it as an identifier of the author of the Bundle. The Info.plist gets ship on the binaries and people can query it at runtime (no one actually do that, but they could). I choose my initials (`MSDC`) or the company I work for and mark the frameworks being developed.

**Comment by Ben-G** [comment]
Thx a lot for the info :+1: 

Sorry, I realized a few more things in the PR. It is changing the indentation of all of the existing code. It would be great if this PR would only touch the project configuration.

> Change the licensing from each file to the Info plist, thus the ugly header need not be repeated.

Also, I somehow like the precursor that contains the target, file and author information of the top of each file. Would you mind leaving it in the files? (I know, tastes are different :smile:). I will update it to refer to the MIT license instead of "All Rights Reserved".

Sorry for the late additional comments; hadn't realized these changes when glancing over the PR.

**Comment by dehesa** [comment]
No worries.

I reverted Validated.swift and the test file to their previous _ugly header_ format 😀 and indentation (I am sad you are in the _wrong_ side of the code indentation taste, but it is not a big deal 😜).

Can I ask you why you like those prefilled Xcode headers? I have always found that they don't provide much information, often just repeat the same word several times, fill up space and discourage people on sharing code on a library since often the file keeps the name of the first author, but not the developers that came later and touch the codebase.

**Comment by Ben-G** [comment]
> Can I ask you why you like those prefilled Xcode headers? I have always found that they don't provide much information, often just repeat the same word several times, fill up space

I don't really have a good argument against this. Your reasoning is very rationale, mine is mostly aesthetic. I like that they provide some context and I like a little bit of margin before the actual code begins. As I said, taste differs :wink: 

> and discourage people on sharing code on a library since often the file keeps the name of the first author, but not the developers that came later and touch the codebase.

This one is a good point. I'm happy to replace my name with `Validated Contributors`.

I'm not sure why, but I'm still seeing a lot of indentation changes on both implementation and test files?

**Comment by dehesa** [comment]
I don't know why those weird empty-space indentations appeared. I tried to fixed them. Let me know what you think.

**Comment by Ben-G** [comment]
This looks great! And thanks a lot for your patience :+1: :tada:

**Comment by Ben-G** [comment]
@dehesa after reflecting on this a little, I came to agree with you and have removed the preamble from the source files ;)

**Comment by dehesa** [comment]
Hey, that is great to hear. I know it is a small change, but I believe these little details make projects approachable and warm to new developers. Thank you!

**Pull request merged**
