### PR TITLE
Added wrapper validators to allow logical arithmetic and/or/not

### PR DESCRIPTION
**Pull request by tomquist**
Hey Benji,
this pull request basically replaces Validated2 and Validated3 and allows validations like this:

```
struct User {
    let isAuthor: Bool
    let isAdmin: Bool
}

struct UserIsAuthor: Validator {
    typealias WrappedType = User
    static func validate(value: User) -> Bool {
        return value.isAuthor
    }
}
struct UserIsAdmin: Validator {
    typealias WrappedType = User
    static func validate(value: User) -> Bool {
        return value.isAdmin
    }
}

typealias AdminOrAuthorUser = Validated<User, Or<UserIsAdmin, UserIsAuthor>>
typealias AdminAndAuthorUser = Validated<User, And<UserIsAdmin, UserIsAuthor>>
typealias NonAuthorUser = Validated<User, Not<UserIsAuthor>>
```

### CODE REVIEW

**Comment by Ben-G** [comment]
@tomquist This is a great idea!

To replace `Validated3` you would have to use two `And` validators right now? With that in mind it might make sense to keep `Validated3` around? Or provide an `And` that takes 3 Validators? I think it's important to keep the important use cases simple.

When merging this we also need to update docs and examples so this might take a little time. But definitely want these changes in :100:

**Comment by tomquist** [comment]
Yes, to get something similar to `Validated3` you could do `Validated<User, And<And<A, B>, C>>` which is not that pretty. However, in my opinion we should completely get rid of `Validated2` and `Validated3` and only have a single `Validated` type. This also allows a simpler implementation of #2 for which I also prepared a pull request already (not submitted yet).

**Comment by Ben-G** [comment]
@tomquist Would like to merge this, but I think it would be best to merge into `development` branch that I just created. That way the master branch, including documentation will be up to date with the latest release.

I'll then update docs and merge into `master` when drafting the next release.

**Comment by Ben-G** [comment]
Will unfortunately require closing this PR and opening a new one.

**Comment by tomquist** [comment]
Opened a new pull request #5

**Pull request closed without merging**
